spring: 
  profiles:
    active: dev
---
# 开发环境 
spring:
  application:
    name: config-server-dev
    profiles: dev 

---
# 测试环境 
spring:
  application:
    name: config-server-test
    profiles: test